# This compose file defines an Aptos Validator deployment.
# Read the README.md files for instruction on how to install aptos-node

version: "3.8"
services:
  haproxy:
    image: haproxytech/haproxy-debian:2.2
    networks:
      - shared
    volumes:
      - type: bind
        source: ./haproxy-fullnode.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
      - type: bind
        source: ./blocked.ips
        target: /usr/local/etc/haproxy/blocked.ips
    expose:
      - 6180
      - 6181
      - 9101
      - 8180
    ports:
      - "6180:6180"
      - "6181:6181"
      - "8180:8180"
      - "9101:9101"

  fullnode:
    image: debian:latest
    networks:
      - shared
    volumes:
      - type: bind
        source: ../../../../target/release/axum-test
        target: /usr/bin/listener
    command: ["listener"]
    restart: unless-stopped
    expose:
      - 6190
      - 6180
      - 6181
      - 9101
      - 8080

networks:
    hostnet:
      external: true
      name: host

    shared:
        name: "aptos-docker-compose-shared"
        ipam:
          config:
            - subnet: 172.16.1.0/24

volumes:
  aptos-validator:
    name: aptos-validator
