[package]
name = "aptos-consensus-types"
description = "Aptos consensus types"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-bitvec = { workspace = true }
aptos-crypto = { workspace = true }
aptos-crypto-derive = { workspace = true }
aptos-executor-types = { workspace = true }
aptos-infallible = { workspace = true }
aptos-short-hex-str = { workspace = true }
aptos-types = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
mirai-annotations = { workspace = true }
proptest = { workspace = true, optional = true }
rayon = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
aptos-types = { workspace = true, features = ["fuzzing"] }
proptest = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "aptos-types/fuzzing", "aptos-crypto/fuzzing"]
