name: "Check SDK examples"
on:
  pull_request:
  push:
    branches:
      - devnet

jobs:
  # Run the TS SDK examples. Note: There are small windows where these examples
  # might be able to fail. For example, if we released a new devnet and SDK with
  # an incompatible change, but haven't updated the examples to use the new SDK.
  # That's why this is a separate job, because there are times when it could fail,
  # whereas there is no reason why the test-sdk-confirm-client-generated-publish
  # job should fail. These could also fail because we run them against devnet,
  # whereas we run the test-sdk-confirm-client-generated-publish against a node
  # built from the same commit and run as part of that CI job.
  run-examples:
    runs-on: ubuntu-latest
    env:
      APTOS_NODE_URL: https://fullnode.devnet.aptoslabs.com
      APTOS_FAUCET_URL: https://faucet.devnet.aptoslabs.com
      FAUCET_AUTH_TOKEN: ${{ secrets.DEVNET_TAP_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.2

      # Run example code in typescript.
      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: ts-example-test
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./ecosystem/typescript/sdk/examples/typescript && pnpm install && pnpm test

      # Run example code in javascript.
      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: js-example-test
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./ecosystem/typescript/sdk/examples/javascript && pnpm install && pnpm test

  run-python-examples:
    runs-on: ubuntu-latest
    env:
      APTOS_NODE_URL: https://fullnode.devnet.aptoslabs.com/v1
      APTOS_FAUCET_URL: https://faucet.devnet.aptoslabs.com
      FAUCET_AUTH_TOKEN: ${{ secrets.DEVNET_TAP_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2

      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: py-example-test
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./ecosystem/python/sdk && poetry install && make test && make examples
