# This defines a workflow to build and release a new version of the aptos CLI.
# In order to trigger it go to the Actions Tab of the Repo, click "Release CLI" and then "Run Workflow".

name: "Release CLI"

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: "The release tag to create. E.g. `aptos-cli-v0.2.3`:"
      source_git_ref_override:
        type: string
        required: false
        description: "GIT_SHA_OVERRIDE: Use this to override the Git SHA1, branch name (e.g. devnet) or tag to build the binaries from. Defaults to the workflow Git REV, but can be different than that:"
      release_title:
        type: string
        required: false
        description: 'Name of the release, e.g. "Aptos CLI devnet release 2022-06-09":'

jobs:
  build-ubuntu20-binary:
    name: "Build Ubuntu 20.04 binary"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - uses: ./.github/actions/rust-setup
      - name: Build CLI
        run: scripts/cli/build_cli_release.sh "Ubuntu"
      - name: Upload Binary
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        with:
          name: cli-builds
          path: aptos-cli-*.zip

  build-ubuntu22-binary:
    name: "Build Ubuntu 22.04 binary"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - uses: ./.github/actions/rust-setup
      - name: Build CLI
        run: scripts/cli/build_cli_release.sh "Ubuntu-22.04"
      - name: Upload Binary
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        with:
          name: cli-builds
          path: aptos-cli-*.zip

  build-os-x-binary:
    name: "Build OS X binary"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - name: Build CLI
        run: scripts/cli/build_cli_release.sh "MacOSX"
      - name: Upload Binary
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        with:
          name: cli-builds
          path: aptos-cli-*.zip

  build-windows-binary:
    name: "Build Windows binary"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ github.event.inputs.source_git_ref_override }}
      - name: Build CLI
        run: scripts\cli\build_cli_release.ps1
      - name: Upload Binary
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        with:
          name: cli-builds
          path: aptos-cli-*.zip

  release-binaries:
    name: "Release binaries"
    needs:
      - build-ubuntu20-binary
      - build-ubuntu22-binary
      - build-os-x-binary
      - build-windows-binary
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      pull-requests: "read"
    steps:
      - name: Download prebuilt binaries
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # pin@v3
        with:
          name: cli-builds
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # pin@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.release_tag }}"
          prerelease: false
          title: "${{ github.event.inputs.release_title }}"
          files: |
            aptos-cli-*.zip
