name: Continuous E2E Network Partition Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run-forge-network-partition-test:
    uses: ./.github/workflows/run-forge.yaml
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-network-partition
      # Run for 15 minutes
      FORGE_RUNNER_DURATION_SECS: 900
      FORGE_TEST_SUITE: network_partition
      POST_TO_SLACK: true
