name: Continuous E2E Validator Reboot Stress Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run-forge-validator-reboot-stress-test:
    uses: ./.github/workflows/run-forge.yaml
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-validator-reboot-stress
      # Run for 40 minutes
      FORGE_RUNNER_DURATION_SECS: 2400
      FORGE_TEST_SUITE: validator_reboot_stress_test
      POST_TO_SLACK: true
