name: Continuous E2E Consensus Stress Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  ### Please remember to use different namespace for different tests
  # Performance test in an optimal setting
  run-forge-consensus-stress-test:
    uses: ./.github/workflows/run-forge.yaml
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-consensus-stress-test
      FORGE_RUNNER_DURATION_SECS: 2400
      FORGE_TEST_SUITE: consensus_stress_test
      POST_TO_SLACK: true
