name: Continuous E2E State Sync Failures Catching Up Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run-forge-state-sync-failures-catching-up-test:
    uses: ./.github/workflows/run-forge.yaml
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-state-sync-failures-catching-up-test
      FORGE_CLUSTER_NAME: aptos-forge-big-1
      FORGE_RUNNER_DURATION_SECS: 900
      FORGE_TEST_SUITE: state_sync_failures_catching_up
      POST_TO_SLACK: true
      FORGE_ENABLE_FAILPOINTS: true
