name: Continuous E2E Compat Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run-forge-compat:
    uses: ./.github/workflows/run-forge.yaml
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-compat
      # Run for 5 minutes
      FORGE_RUNNER_DURATION_SECS: 300
      # This will upgrade from testnet branch to the latest main
      FORGE_TEST_SUITE: compat
      IMAGE_TAG: testnet
      POST_TO_SLACK: true
