name: Continuous E2E Performance Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  ### Please remember to use different namespace for different tests
  # Performance test in an optimal setting with the performance profile
  run-forge-performance:
    uses: ./.github/workflows/run-forge.yaml
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-performance
      # Run for 2 hours
      FORGE_RUNNER_DURATION_SECS: 7200
      # Land blocking is performance test
      FORGE_TEST_SUITE: land_blocking
      # Enable performance profile
      FORGE_ENABLE_PERFORMANCE: true
      POST_TO_SLACK: true
