name: Continuous E2E Different Node Speed And Reliability Test

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  ### Please remember to use different namespace for different tests
  # Performance test in an optimal setting
  run-forge-different-node-speed-and-reliability-test:
    uses: ./.github/workflows/run-forge.yaml
    secrets: inherit
    with:
      FORGE_NAMESPACE: forge-different-node-speed-and-reliability-test
      FORGE_RUNNER_DURATION_SECS: 900
      FORGE_TEST_SUITE: different_node_speed_and_reliability_test
      POST_TO_SLACK: true
      FORGE_ENABLE_FAILPOINTS: true
