name: "Lint Helm Charts"

on:
  workflow_call:
    inputs:
      GIT_SHA:
        required: false
        type: string

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}
          # Get enough commits to compare to
          fetch-depth: 100

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@60f4aabced9b4718c75acef86d42ffb631c4403a # pin@v29.0.3

      - name: Setup Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # pin@v4

      - name: Install Python Dependencies
        run: pip install -r testsuite/requirements.txt

      - name: Should run lint
        run: >
          python testsuite/determinator.py changed-files --github-output-key
          SHOULD_RUN --pattern 'terraform/helm/.*' ${{
          steps.changed-files.outputs.all_changed_files }}
        id: should-run-tests

      - name: Run Helm Lint
        if: steps.should-run-tests.outputs.SHOULD_RUN == 'true'
        run: python testsuite/lint.py helm terraform/helm/*
