name: "Run Python Tests"

on:
  workflow_call:
    inputs:
      GIT_SHA:
        required: false
        type: string

jobs:
  python-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}
          # Get enough commits to compare to
          fetch-depth: 100

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@60f4aabced9b4718c75acef86d42ffb631c4403a # pin@v29.0.3

      - name: Setup Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # pin@v4

      - name: Install Python Dependencies
        run: pip install -r testsuite/requirements.txt

      - name: Should run tests
        run: >
          python testsuite/determinator.py changed-files --github-output-key SHOULD_RUN --pattern 'testsuite/.*py' ${{steps.changed-files.outputs.all_changed_files }}
        id: should-run-tests

      - name: Install Python Dev Dependencies
        if: steps.should-run-tests.outputs.SHOULD_RUN == 'true'
        run: pip install pyright black

      - name: Run python static type checker
        if: steps.should-run-tests.outputs.SHOULD_RUN == 'true'
        run: pyright testsuite/**/*.py

      - name: Run python fmt
        if: steps.should-run-tests.outputs.SHOULD_RUN == 'true'
        run: black --check --diff testsuite

      - name: Run python unit tests
        if: steps.should-run-tests.outputs.SHOULD_RUN == 'true'
        run: python -m unittest testsuite/*test*.py
