[package]
name = "aptos-transaction-emitter-lib"
description = "Library for Aptos transaction emitter"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
again = { workspace = true }
anyhow = { workspace = true }
aptos = { workspace = true }
aptos-config = { workspace = true }
aptos-crypto = { workspace = true }
aptos-framework = { workspace = true }
aptos-global-constants = { workspace = true }
aptos-infallible = { workspace = true }
aptos-logger = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-sdk = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
