name: Setup docker buildx

runs:
  using: composite
  steps:
    - name: setup docker context for buildx
      id: buildx-context
      shell: bash
      run: docker context create builders
    - name: setup docker buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # pin@v2
      with:
        endpoint: builders
        version: v0.8.2
