[package]
name = "aptos-secure-storage"
description = "Aptos's Persistent, Secure Storage"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-crypto = { workspace = true }
aptos-github-client = { workspace = true }
aptos-infallible = { workspace = true }
aptos-logger = { workspace = true }
aptos-schemadb = { workspace = true }
aptos-temppath = { workspace = true }
aptos-time-service = { workspace = true }
aptos-vault-client = { workspace = true }
base64 = { workspace = true }
bcs = { workspace = true }
chrono = { workspace = true }
enum_dispatch = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
aptos-crypto = { workspace = true, features = ["fuzzing"] }
aptos-crypto-derive = { workspace = true }
aptos-schemadb = { workspace = true, features = ["fuzzing"] }
rand = { workspace = true }

[features]
fuzzing = ["aptos-crypto/fuzzing"]
testing = []
