[profile.ci]
# Show skipped tests in the CI output.
status-level = "skip"
# Show output for all tests as soon as they fail and at the end of the test run.
failure-output = "immediate-final"
# Cancel test run on the first failure. Accounts for retries.
fail-fast = true

junit = { path = "junit.xml" }

[profile.smoke-coverage]
test-threads = 6
retries = 3
status-level = "skip"
failure-output = "immediate-final"
junit = { path = "junit.xml" }
