[package]
name = "generate-format"
description = "Aptos core type checker to ensure compatibility"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-api-types = { workspace = true }
aptos-config = { workspace = true }
aptos-consensus = { workspace = true, features = ["fuzzing"] }
aptos-consensus-types = { workspace = true }
aptos-crypto = { workspace = true }
aptos-crypto-derive = { workspace = true }
aptos-network = { workspace = true }
aptos-types = { workspace = true }
bcs = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
rand = { workspace = true }
serde = { workspace = true }
serde-reflection = { workspace = true }
serde_yaml = { workspace = true }
structopt = { workspace = true }

[[bin]]
name = "compute"
path = "src/compute.rs"
test = false
