# -- Default image tag to use for all aptos images
imageTag: devnet

genesis:
  # -- Validator username prefix, used to get genesis secrets. This should be the fullname for the aptos-node helm release
  username_prefix: aptos-node
  # -- Number of validators deployed in this testnet
  numValidators:
  # -- Aptos Chain ID
  chain_id:

waypoint:
  image:
    # -- Image repo to use for serving waypoint and genesis
    repo: joseluisq/static-web-server
    # -- Image tag to use for serving waypoint and genesis
    tag: 2.12@sha256:a3b147754be4c38ce96189c4dbaa708c36f39dfcc043c470812c33dd53fea7d0
    # -- Image pull policy to use for waypoint image
    pullPolicy: IfNotPresent
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      cpu: 200m
      memory: 512Mi

load_test:
  # -- Whether to enable the load test CronJob
  enabled: false
  image:
    # -- Image repo to use for tools image for running load tests
    repo: aptoslabs/tools
    # -- Image tag to use for tools image
    tag:
    # -- Image pull policy to use for tools image
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 1
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # -- How many minutes between load test runs
  intervalMins: 15
  # -- The fullnode groups to target
  fullnode:
    groups:
    - name: fullnode
  config:
    # -- The number of fullnode groups to run traffic against
    numFullnodeGroups:
    # -- The private key used to mint to fund load test
    mint_key:
    # -- Number of transactions outstanding in mempool
    mempool_backlog: 5000
    # -- Whether to target a constant TPS, or 0 if not used. Cannot be used with mempool_backlog.
    target_tps: 0
    # -- How long to emit transactions for
    duration: 300
    # -- How long to wait for transactions to be expired
    txn_expiration_time_secs: 30
    # -- Whether to submit transactions through validator REST API
    use_validators: false

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

service:
  # -- If set, the base domain name to use for External DNS
  domain:

ingress:
  # -- The ACM certificate to install on the ingress
  acm_certificate:
  # -- The ARN of the WAF ACL to install on the ingress
  wafAclArn:
  # -- List of CIDRs to accept traffic from
  loadBalancerSourceRanges:
  # -- Whether to enable session stickiness on the underlying load balancer
  enableStickyness: true
  # -- If stickiness is enabled, how long the session cookie should last
  cookieDurationSeconds: 86400
