apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backup.fullname" . }}-restore-{{ randAlpha 4 | lower }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
    app.kubernetes.io/name: restore
spec:
  completions: 0
  template:
    metadata:
      labels:
        {{- include "backup.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: restore
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      {{- with .Values.restore }}
      containers:
      - name: restore
        image: {{ .image.repo }}:{{ .image.tag | default $.Values.imageTag }}
        imagePullPolicy: {{ .image.pullPolicy }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        command:
        - sh
        - -c
        - |-
          set -ex
          # cleanup aptosdb
          if [ ! -f /opt/aptos/data/restore-uid ] || [ "$(cat /opt/aptos/data/restore-uid)" != "$CONTROLLER_UID" ]; then
              rm -rf /opt/aptos/data/db
              echo "$CONTROLLER_UID" > /opt/aptos/data/restore-uid
          fi
          # start restore process
          /usr/local/bin/db-restore --concurrent-downloads {{ .config.concurrent_downloads }}{{ range .config.trusted_waypoints }} --trust-waypoint {{ . }}{{ end }} --target-db-dir /opt/aptos/data/db auto --metadata-cache-dir /tmp/aptos-restore-metadata command-adapter --config /opt/aptos/etc/{{ .config.location }}.yaml
        env:
        - name: RUST_LOG
          value: "debug"
        - name: RUST_BACKTRACE
          value: "1"
        {{- if (include "backup.pushMetricsEndpoint" $) }}
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PUSH_METRICS_ENDPOINT
          value: "{{- include "backup.pushMetricsEndpoint" $ }}/api/v1/import/prometheus?extra_label=role={{- .jobName | default "db_restore" }}&extra_label=kubernetes_pod_name=$(KUBERNETES_POD_NAME)"
        {{- end }}
        - name: CONTROLLER_UID
          valueFrom:
            fieldRef:
              fieldPath: "metadata.labels['controller-uid']"
        {{- include "backup.backupEnvironment" (dict "config" .config "era" (default $.Values.chain.era .config.restore_era)) | nindent 8 }}
        volumeMounts:
        - name: backup-config
          mountPath: /opt/aptos/etc
        - name: aptos-data
          mountPath: /opt/aptos/data
        - name: tmp
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
        fsGroup: 6180
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      volumes:
      - name: backup-config
        configMap:
          name: {{ include "backup.fullname" . }}-backup
      - name: tmp
        emptyDir: {}
      - name: aptos-data
        persistentVolumeClaim:
          claimName: {{ include "backup.persistentVolumeClaim" . }}
      serviceAccountName: {{ include "backup.serviceAccount" . }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{.Values.imagePullSecret}}
      {{- end }}
