{{- range $secretName, $secretKeyValuePairs := .Values.secretVars }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := $secretKeyValuePairs }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
