[package]
name = "aptos-db"
description = "Aptos database"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-accumulator = { workspace = true }
aptos-config = { workspace = true }
aptos-crypto = { workspace = true }
aptos-db-indexer = { workspace = true }
aptos-executor-types = { workspace = true }
aptos-infallible = { workspace = true }
aptos-jellyfish-merkle = { workspace = true }
aptos-logger = { workspace = true }
aptos-metrics-core = { workspace = true }
aptos-proptest-helpers = { workspace = true, optional = true }
aptos-rocksdb-options = { workspace = true }
aptos-schemadb = { workspace = true }
aptos-scratchpad = { workspace = true }
aptos-state-view = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-temppath = { workspace = true, optional = true }
aptos-types = { workspace = true }
aptos-vm = { workspace = true }
arc-swap = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
lru = { workspace = true }
move-core-types = { workspace = true }
move-resource-viewer = { workspace = true }
num-derive = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
aptos-executor-types = { workspace = true }
aptos-jellyfish-merkle = { workspace = true, features = ["fuzzing"] }
aptos-proptest-helpers = { workspace = true }
aptos-schemadb = { workspace = true, features = ["fuzzing"] }
aptos-scratchpad = { workspace = true, features = ["fuzzing"] }
aptos-temppath = { workspace = true }
aptos-types = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "aptos-proptest-helpers", "aptos-temppath", "aptos-crypto/fuzzing", "aptos-jellyfish-merkle/fuzzing", "aptos-types/fuzzing", "aptos-executor-types/fuzzing", "aptos-schemadb/fuzzing", "aptos-scratchpad/fuzzing"]
consensus-only-perf-test = []
