validator:
  enableNetworkPolicy: false
  rust_log: debug,hyper=off
  # force enable the telemetry service to try to send telemetry
  force_enable_telemetry: true

fullnode:
  # at most one VFN per validator, depending on numFullnodeGroups
  groups:
  - name: fullnode
    replicas: 1
  rust_log: debug,hyper=off
  # force enable the telemetry service to try to send telemetry
  force_enable_telemetry: true

# Make all services internal NodePort and open all ports
# NodePort is required for ChaosMesh to function correctly: https://github.com/chaos-mesh/chaos-mesh/issues/3278#issuecomment-1134248492
service:
  validator:
    external:
      type: "NodePort"
    internal:
      type: "NodePort"
    enableRestApi: true
    enableMetricsPort: true

  fullnode:
    external:
      type: "NodePort"
    internal:
      type: "NodePort"
    enableRestApi: true
    enableMetricsPort: true

# always assume we're spinning up a testnet and doing genesis rather than using the single validator test mode
loadTestGenesis: false
# always run forge in privileged mode for extra testing capability
enablePrivilegedMode: true
# always run forge with profiling enabled
pyroscope:
  enabled: true
