[tool.poetry]
name = "aptos-sdk"
version = "0.5.0"
description = "Aptos SDK"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
httpx = "^0.23.0"
mypy = "^0.982"
PyNaCl = "^1.5.0"
python = ">=3.7,<4.0"

[tool.poetry.dev-dependencies]
autoflake = "1.4.0"
black = "^22.6.0"
flake8 = ">=3.8.3,<6.0.0"
isort = "^5.10.1"
mypy = "^0.982"
mypy-extensions = "^0.4.3"
typing-extensions = "^4.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
