[package]
name = "aptos-forge"
description = "Aptos end to end test framework"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
again = { workspace = true }
anyhow = { workspace = true, features = ["backtrace"] }
aptos = { workspace = true }
aptos-cached-packages = { workspace = true }
aptos-config = { workspace = true }
aptos-db = { workspace = true }
aptos-framework = { workspace = true }
aptos-genesis = { workspace = true }
aptos-global-constants = { workspace = true }
aptos-infallible = { workspace = true }
aptos-inspection-service = { workspace = true }
aptos-logger = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-retrier = { workspace = true }
aptos-sdk = { workspace = true }
aptos-secure-storage = { workspace = true }
aptos-state-sync-driver = { workspace = true }
aptos-transaction-emitter-lib = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
hyper-tls = { workspace = true }
itertools = { workspace = true }
json-patch = { workspace = true }
k8s-openapi = { workspace = true }
kube = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
prometheus-http-query = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde ={ workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
structopt = { workspace = true }
tempfile = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[features]
default = []
testing = ["aptos-global-constants/testing"]
