[package]
name = "aptos-release-builder"
description = "Tooling for building the governance proposal script used for the network"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos = { workspace = true }
aptos-crypto = { workspace = true }
aptos-gas = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-temppath = { workspace = true }
aptos-types = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
move-core-types = { workspace = true }
move-model = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[[bin]]
name = "aptos-release-builder"
path = "src/main.rs"
