[package]
name = "aptos-state-sync-driver"
description = "The driver for state sync"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-config = { workspace = true }
aptos-consensus-notifications = { workspace = true }
aptos-crypto = { workspace = true }
aptos-data-client = { workspace = true }
aptos-data-streaming-service = { workspace = true }
aptos-event-notifications = { workspace = true }
aptos-executor-types = { workspace = true }
aptos-infallible = { workspace = true }
aptos-logger = { workspace = true }
aptos-mempool-notifications = { workspace = true }
aptos-metrics-core = { workspace = true }
aptos-runtimes = { workspace = true }
aptos-schemadb = { workspace = true }
aptos-scratchpad = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-time-service = { workspace = true }
aptos-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
aptos-channels = { workspace = true }
aptos-crypto = { workspace = true }
aptos-db = { workspace = true }
aptos-executor = { workspace = true }
aptos-executor-test-helpers = { workspace = true }
aptos-genesis = { workspace = true, features = ["testing"] }
aptos-network = { workspace = true }
aptos-storage-service-client = { workspace = true }
aptos-storage-service-types = { workspace = true }
aptos-temppath = { workspace = true }
aptos-time-service = { workspace = true, features = ["async", "testing"] }
aptos-vm = { workspace = true }
aptos-vm-genesis = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
mockall = { workspace = true }
move-core-types = { workspace = true }
rand = { workspace = true }
