[package]
name = "smoke-test"
description = "Aptos end to end tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos = { workspace = true, features = ["fuzzing"] }
aptos-bitvec = { path = "../../crates/aptos-bitvec" }
aptos-cached-packages = { workspace = true }
aptos-config = { workspace = true }
aptos-consensus = { workspace = true }
aptos-crypto = { workspace = true }
aptos-debugger = { workspace = true }
aptos-faucet = { workspace = true }
aptos-forge = { workspace = true }
aptos-framework = { workspace = true }
aptos-gas = { workspace = true, features = ["testing"] }
aptos-global-constants = { workspace = true }
aptos-indexer = { workspace = true }
aptos-keygen = { workspace = true }
aptos-release-builder = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-rosetta = { workspace = true }
aptos-sdk = { workspace = true }
aptos-temppath = { workspace = true }
aptos-types = { workspace = true }
aptos-vm = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
diesel = { workspace = true }
hex = { workspace = true }
move-core-types = { workspace = true }
proptest = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
aptos-backup-cli = { workspace = true }
aptos-genesis = { workspace = true }
aptos-infallible = { workspace = true }
aptos-logger = { workspace = true }
aptos-secure-storage = { workspace = true }
aptos-time-service = { workspace = true }
aptos-vault-client = { workspace = true }
aptos-writeset-generator = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde_yaml = { workspace = true }
