# Severeties: info, warning, [error, critical]
# Last 2 items are high urgency

global:

route:
  group_by: ["instance", "kubernetes_pod_name", "role"]

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 10m

  # A default receiver
  receiver: "default"

  # The child route trees.
  # https://prometheus.io/docs/alerting/latest/configuration/#route
  routes: {{ .Values.monitoring.alertmanager.alertRouteTrees | toJson }}

# A list of notification receivers
# https://prometheus.io/docs/alerting/latest/configuration/#receiver
receivers: {{ .Values.monitoring.alertmanager.alertReceivers | toJson }}
