chain:
  name:
validator:
  name:
fullnode:
  name:

monitoring:
  prometheus:
    fullKubernetesScrape: false
    deleteWal: false
    tsdb_retention_time: 15d
    tsdb_min_block_duration: 30m
    tsdb_max_block_duration: 1h
    remote_write:
      enabled: false
      url:
      region:
    image:
      repo: prom/prometheus
      tag: v2.34.0@sha256:cb42332b66ac51a05c52f255e48a4496c0a172676093123bf28b37762009e78a
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1.5Gi
      requests:
        cpu: 1
        memory: 1.5Gi
    storage:
      class:
      size: 100Gi
  pushgateway:
    image:
      repo: prom/pushgateway
      tag: v1.4.1@sha256:b561435cb17ee816c5d90c2408bcc1ffe25304f1608e18db16a3969f6cc44626
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 0.1
        memory: 128Mi
      requests:
        cpu: 0.1
        memory: 128Mi
  alertmanager:
    alertRouteTrees:
      - match:
          severity: critical
        receiver: 'critical'
      - match:
          severity: error
        receiver: 'error'
    alertReceivers:
      - name: 'critical'
      - name: 'error'
      - name: 'default'
    image:
      repo: prom/alertmanager
      tag: v0.24.0@sha256:b1ba90841a82ea24d79d4e6255b96025a9e89275bec0fae87d75a5959461971e
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 0.1
        memory: 128Mi
      requests:
        cpu: 0.1
        memory: 128Mi
  grafana:
    image:
      repo: grafana/grafana
      tag: 9.0.9@sha256:4a6b9d8d88522d2851f947f8f84cca10b6a43ca26d5e93102daf3a87935f10a5
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 256Mi
      requests:
        cpu: 1
        memory: 256Mi
    googleAuth:
    config:
    env:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    annotations: {}

service:
  domain:
  external:
    type: LoadBalancer
  monitoring:
    loadBalancerSourceRanges:

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  annotations:

kube-state-metrics:
  enabled: false
  namespaceOverride: kube-system
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

prometheus-node-exporter:
  enabled: false
  namespaceOverride: kube-system
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
