name: "Send Message"
description: |
  Sends the contents of a file as a slack message.
inputs:
  payload-file:
    description: Message file.  If the file does not exist, silently proceed without sending a message.
    required: false
  webhook:
    description: Webhook for the message.
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        build_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        ./.github/actions/slack-file/message_file_to_slack.sh -w "${WEBHOOK}" -f "${PAYLOAD_FILE}" -u "${build_url}" -d
      shell: bash
      env:
        PAYLOAD_FILE: ${{ inputs.payload-file }}
        WEBHOOK: ${{ inputs.webhook }}
