[package]
name = "aptos-rosetta-cli"
description = "Aptos Rosetta CLI for testing"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos = { workspace = true }
aptos-logger = { workspace = true }
aptos-rosetta = { workspace = true }
aptos-types = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

