name: "CI Environment Teardown"
description: "Teardown the environment for CI jobs"

runs:
  using: "composite"
  steps:
    - name: Check for changed and untracked files
      run: ./scripts/changed-files.sh
      shell: bash
    - name: Clean target directory
      run: |
        rm -rf ./target/x-scratch ./target/forge
      shell: bash
