[package]
name = "aptos-transactional-test-harness"
description = "Transactional testing framework for Move"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-api-types = { workspace = true }
aptos-cached-packages = { workspace = true }
aptos-crypto = { workspace = true }
aptos-framework = { workspace = true }
aptos-gas = { workspace = true }
aptos-language-e2e-tests = { workspace = true }
aptos-state-view = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-types = { workspace = true }
aptos-vm = { workspace = true }
aptos-vm-genesis = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
move-binary-format = { workspace = true, features = [ "fuzzing" ] }
move-command-line-common = { workspace = true }
move-compiler = { workspace = true }
move-core-types = { workspace = true, features = [ "fuzzing" ] }
move-resource-viewer = { workspace = true }
move-transactional-test-runner = { workspace = true }
move-vm-runtime = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
datatest-stable = { workspace = true }

[[test]]
name = "tests"
harness = false
