[package]
name = "language-e2e-testsuite"
description = "Move language e2e tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-block-executor = { workspace = true }
aptos-cached-packages = { workspace = true }
aptos-crypto = { workspace = true }
aptos-framework = { workspace = true }
aptos-gas = { workspace = true, features = ["testing"] }
aptos-keygen = { workspace = true }
aptos-language-e2e-tests = { workspace = true }
aptos-logger = { workspace = true }
aptos-state-view = { workspace = true }
aptos-types = { workspace = true }
aptos-vm = { workspace = true }
aptos-vm-genesis = { workspace = true }
aptos-writeset-generator = { workspace = true }
bcs = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true }
move-ir-compiler = { workspace = true }
proptest = { workspace = true }
serde = { workspace = true }

[features]
default = ["aptos-cached-packages/fuzzing"]
