{{- if .Values.podSecurityPolicy }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "aptos-validator.fullname" . }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
  - ALL
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  supplementalGroups:
    rule: MayRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MayRunAs
    ranges:
    - min: 1
      max: 65535
  seLinux:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aptos-validator.fullname" . }}-psp
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "aptos-validator.fullname" . }}

---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "aptos-validator.fullname" . }}-haproxy
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
  - ALL
  allowedCapabilities:
  - SYS_RESOURCE
  - SETUID
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  supplementalGroups:
    rule: MayRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MayRunAs
    ranges:
    - min: 1
      max: 65535
  seLinux:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aptos-validator.fullname" . }}-psp-haproxy
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "aptos-validator.fullname" . }}-haproxy

{{- end }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aptos-validator.fullname" . }}-psp
roleRef:
  kind: ClusterRole
  name: {{ include "aptos-validator.fullname" . }}-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-validator.serviceAccountName" . }}
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-validator.fullname" . }}-validator
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-validator.fullname" . }}-fullnode

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aptos-validator.fullname" . }}-psp-haproxy
roleRef:
  kind: ClusterRole
  name: {{ include "aptos-validator.fullname" . }}-psp-haproxy
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-validator.fullname" . }}-haproxy

---
{{- if .Values.enablePrivilegedMode }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aptos-validator.fullname" . }}-psp-privileged-aws
roleRef:
  kind: ClusterRole
  name: eks:podsecuritypolicy:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-validator.fullname" . }}-validator
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-validator.fullname" . }}-fullnode
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aptos-validator.fullname" . }}-psp-privileged-gcp
roleRef:
  kind: ClusterRole
  name: gce:podsecuritypolicy:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-validator.fullname" . }}-validator
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-validator.fullname" . }}-fullnode
{{- end }}
