{{- range $i, $e := until (int .Values.numValidators) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptos-validator.fullname" $ }}-{{$i}}-validator
  labels:
    {{- include "aptos-validator.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "aptos-validator.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/name: validator
    app.kubernetes.io/instance: validator-{{$i}}
  type: {{ $.Values.service.validator.internal.type }}
  ports:
  - name: validator
    port: 6180
  - name: fullnode
    port: 6181
  - name: metrics
    port: 9101
  {{- if $.Values.service.validator.enableRestApi }}
  - name: api
    port: 8080
  {{- end }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aptos-validator.fullname" $ }}-{{$i}}-validator-e{{ $.Values.chain.era }}
  labels:
    {{- include "aptos-validator.labels" $ | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ $.Values.validator.storage.class }}
  resources:
    requests:
      storage: {{ $.Values.validator.storage.size }}
  {{- if $.Values.validator.storage.labels }}
  selector:
    matchLabels:
      {{- toYaml $.Values.validator.storage.labels | nindent 6}}
  {{- end }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aptos-validator.fullname" $ }}-{{$i}}-validator
  labels:
    {{- include "aptos-validator.labels" $ | nindent 4 }}
    app.kubernetes.io/name: validator
    app.kubernetes.io/instance: validator-{{$i}}
spec:
  serviceName: {{ include "aptos-validator.fullname" $ }}-{{$i}}-validator
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "aptos-validator.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/name: validator
      app.kubernetes.io/instance: validator-{{$i}}
  template:
    metadata:
      labels:
        {{- include "aptos-validator.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/name: validator
        app.kubernetes.io/instance: validator-{{$i}}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        checksum/validator.yaml: {{ tpl ($.Files.Get "files/configs/validator.yaml") $ | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: validator
        image: {{ $.Values.validator.image.repo }}:{{ $.Values.validator.image.tag | default $.Values.imageTag }}
      {{- with $.Values.validator }}
        imagePullPolicy: {{ .image.pullPolicy }}
        {{- if not $.Values.pyroscope.enabled }}
        command: ["/usr/local/bin/aptos-node", "-f", "/opt/aptos/etc/validator.yaml"]
        {{- else }}
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -e
          export PYROSCOPE_APPLICATION_NAME="aptos-node{namespace=${KUBERNETES_NAMESPACE},pod_name=${KUBERNETES_POD_NAME},chain_name={{ $.Values.chain.chain_name | default $.Values.chain.name }}}"
          # to wrap an existing program and profile it
          # TODO: this does not seem to work yet
          # pyroscope exec /usr/local/bin/aptos-node -f /opt/aptos/etc/validator.yaml
          # to profile the entire system
          pyroscope ebpf & /usr/local/bin/aptos-node -f /opt/aptos/etc/validator.yaml
        {{- end }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        env:
        - name: RUST_LOG
          value: {{ .rust_log }}
        {{- if .force_enable_telemetry }}
        - name: APTOS_FORCE_ENABLE_TELEMETRY
          value: "true"
        {{- end }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUST_BACKTRACE
          value: "0"
        {{- if $.Values.pyroscope.enabled }}
        - name: PYROSCOPE_SERVER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.pyroscope.secretName }}
              key: PYROSCOPE_SERVER_ADDRESS
        - name: PYROSCOPE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.pyroscope.secretName }}
              key: PYROSCOPE_AUTH_TOKEN
        - name: PYROSCOPE_SPY_NAME
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.pyroscope.secretName }}
              key: PYROSCOPE_SPY_NAME
        - name: PYROSCOPE_SAMPLE_RATE
          value: "24"
        - name: PYROSCOPE_LOG_LEVEL
          value: error
        {{- end }}
      {{- end }}
        volumeMounts:
        - name: aptos-config
          mountPath: /opt/aptos/etc
        - name: genesis-config
          mountPath: /opt/aptos/genesis
        - name: aptos-data
          mountPath: /opt/aptos/data
        ports:
        - containerPort: 6180
        - containerPort: 6181  # VFN
        - containerPort: 6182  # Public
        - containerPort: 8080
          name: api
        - containerPort: 9101
          name: metrics
        securityContext:
          {{- if $.Values.enablePrivilegedMode }}
          runAsUser: 0
          privileged: true
          {{- else }}
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          {{- end }}
      {{- with $.Values.validator }}
      {{- with $.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- if $.Values.enablePrivilegedMode }}
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        {{- else }}
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
        fsGroup: 6180
        {{- end }}
      {{- end }}
      volumes:
      - name: aptos-config
        configMap:
          name: {{ include "aptos-validator.fullname" $ }}-{{$i}}
      - name: genesis-config
        # Current implementation of `forge::backend::k8s::stateful_set::{set_identity, get_identity}`
        # depends on the position of this volume item within the parent list.
        secret:
          secretName: {{ include "aptos-validator.fullname" $ }}-{{$i}}-genesis-e{{ $.Values.chain.era }}
      - name: aptos-data
        persistentVolumeClaim:
          claimName: {{ include "aptos-validator.fullname" $ }}-{{$i}}-validator-e{{ $.Values.chain.era }}
      serviceAccountName: {{ include "aptos-validator.fullname" $ }}-validator
      {{- if $.Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.imagePullSecret }}
      {{- end }}
{{- end }}
