[package]
name = "aptos-data-streaming-service"
description = "The data streaming service that sends data notifications to clients"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-channels = { workspace = true }
aptos-config = { workspace = true }
aptos-crypto = { workspace = true }
aptos-data-client = { workspace = true }
aptos-id-generator = { workspace = true }
aptos-infallible = { workspace = true }
aptos-logger = { workspace = true }
aptos-metrics-core = { workspace = true }
aptos-network = { workspace = true }
aptos-short-hex-str = { workspace = true }
aptos-types = { workspace = true }
async-trait = { workspace = true }
enum_dispatch = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
aptos-storage-service-types = { workspace = true }
aptos-types = { workspace = true }
claims = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
