[package]
name = "aptos-peer-monitoring-service-client"
description = "The Aptos peer monitoring service (client-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-channels = { workspace = true }
aptos-config = { workspace = true }
aptos-network = { workspace = true }
aptos-peer-monitoring-service-types = { workspace = true }
aptos-types = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
