[package]
name = "aptos-executor-benchmark"
description = "Aptos executor benchmark"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-config = { workspace = true }
aptos-crypto = { workspace = true }
aptos-db = { workspace = true }
aptos-executor = { workspace = true }
aptos-executor-types = { workspace = true }
aptos-genesis = { workspace = true, features = ["testing"] }
aptos-infallible = { workspace = true }
aptos-jellyfish-merkle = { workspace = true }
aptos-logger = { workspace = true }
aptos-push-metrics =  { workspace = true }
aptos-schemadb = { workspace = true }
aptos-scratchpad = { workspace = true }
aptos-sdk = { workspace = true }
aptos-state-view = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-types = { workspace = true }
aptos-vm = { workspace = true }
chrono = { workspace = true }
criterion = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
structopt = { workspace = true }
toml = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }

[dev-dependencies]
aptos-temppath = { workspace = true }

[features]
default = []
fuzzing = ["aptos-config/fuzzing", "aptos-crypto/fuzzing", "aptos-types/fuzzing"]

[[bench]]
name = "executor_benchmark"
harness = false
