[package]
name = "aptos-event-notifications"
description = "The notification service offered by state sync for on-chain events"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-channels = { workspace = true }
aptos-id-generator = { workspace = true }
aptos-infallible = { workspace = true }
aptos-state-view = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-types = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
aptos-crypto = { workspace = true }
aptos-db = { workspace = true }
aptos-executor-test-helpers = { workspace = true }
aptos-temppath = { workspace = true }
aptos-vm = { workspace = true }
aptos-vm-genesis = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
