runs:
  using: composite
  steps:
    - uses: ./.github/actions/rust-setup
    - name: install dependencies
      shell: bash
      run: |
        echo "${HOME}/bin/" >> $GITHUB_PATH # default INSTALL_DIR to path
        scripts/dev_setup.sh -b -i awscli # install individual tool awscli in batch mode
        sudo apt-get update -y && sudo apt-get install -y expect
    - name: Build CLI binaries in release mode
      shell: bash
      run: cargo build --release -p aptos-backup-cli --bin replay-verify --bin db-backup
    - name: query latest version in backup, at the same time, pre-heat metadata cache
      shell: bash
      run: |
        set -o nounset -o errexit -o pipefail
        target/release/db-backup one-shot query backup-storage-state \
        --metadata-cache-dir ./metadata-cache \
        command-adapter --config terraform/helm/fullnode/files/backup/$CONFIG_TEMPLATE_NAME \
        | echo LATEST_VERSION=`grep -Po '(?<=latest_transaction_version: )\d+'` \
        | tee -a $GITHUB_ENV
    - name: run verify-modules in parallel
      shell: bash
      run: |
          mkdir local
          cp -r metadata-cache local/
          unbuffer target/release/replay-verify \
          --validate-modules \
          --concurrent-downloads 16 \
          --replay-concurrency-level 4 \
          --metadata-cache-dir ./local/metadata-cache \
          --target-db-dir ./local/db \
          --start-version $LATEST_VERSION \
          command-adapter --config terraform/helm/fullnode/files/backup/s3-public.yaml 2>&1 \
