[package]
name = "aptos-crypto"
description = "Aptos crypto"
version = "0.0.3"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-crypto-derive = { workspace = true }
bcs = { workspace = true }
blst = { workspace = true }
bytes = { workspace = true }
curve25519-dalek = { workspace = true }
digest = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
libsecp256k1 = { workspace = true }
more-asserts = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rand = { workspace = true }
rand_core = { workspace = true }
ring = { workspace = true }
serde = { workspace = true }
serde-name = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
tiny-keccak = { workspace = true }
x25519-dalek = { workspace = true }

[dev-dependencies]
bitvec = { workspace = true }
blake2 = { workspace = true }
blake2-rfc = { workspace = true }
byteorder = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
trybuild = { workspace = true }

[features]
default = []
assert-private-keys-not-cloneable = []
cloneable-private-keys = []
fuzzing = ["proptest", "proptest-derive", "cloneable-private-keys"]

[[bench]]
name = "bls12381"
harness = false

[[bench]]
name = "ed25519"
harness = false

[[bench]]
name = "hash"
harness = false

[[bench]]
name = "noise"
harness = false

[[bench]]
name = "ristretto255"
harness = false

[[bench]]
name = "secp256k1"
harness = false
