[package]
name = "aptos"
description = "Aptos tool for management of nodes and interacting with the blockchain"
version = "1.0.4"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-backup-cli = { workspace = true }
aptos-bitvec = { workspace = true }
aptos-build-info = { workspace = true }
aptos-cached-packages = { workspace = true }
aptos-config = { workspace = true }
aptos-crypto = { workspace = true }
aptos-faucet = { workspace = true }
aptos-framework = { workspace = true }
aptos-gas = { workspace = true }
aptos-genesis = { workspace = true }
aptos-github-client = { workspace = true }
aptos-global-constants = { workspace = true }
aptos-keygen = { workspace = true }
aptos-logger = { workspace = true }
aptos-node = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-sdk = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-telemetry = { workspace = true }
aptos-temppath = { workspace = true }
aptos-transactional-test-harness = { workspace = true }
aptos-types = { workspace = true }
aptos-vm = { workspace = true, features = ["testing"] }
aptos-vm-genesis = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bcs = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-cli = { workspace = true }
move-command-line-common = { workspace = true }
move-core-types = { workspace = true }
move-package = { workspace = true }
move-prover = { workspace = true }
move-prover-boogie-backend = { workspace = true }
move-symbol-pool = { workspace = true }
move-unit-test = { workspace = true }
move-vm-runtime = { workspace = true, features = [ "testing" ] }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shadow-rs = { workspace = true }
tempfile = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }

[features]
default = []
fuzzing = []
no-upload-proposal = []
indexer = ["aptos-node/indexer"]
cli-framework-test-move = []

[build-dependencies]
shadow-rs = { workspace = true }
