base:
  role: "full_node"
  data_dir: "/opt/aptos/data"
  waypoint:
    from_file: "/opt/aptos/genesis/waypoint.txt"

execution:
  genesis_file_location: "/opt/aptos/genesis/genesis.blob"

full_node_networks:
- network_id:
    private: "vfn"
  listen_address: "/ip4/0.0.0.0/tcp/6181"
  seeds:
    00000000000000000000000000000000d58bc7bb154b38039bc9096ce04e1237:
      addresses:
      - "/ip4/<Validator IP Address>/tcp/6181/noise-ik/f0274c2774519281a8332d0bb9d8101bd58bc7bb154b38039bc9096ce04e1237/handshake/0"
      role: "Validator"

- network_id: "public"
  discovery_method: "onchain"
  listen_address: "/ip4/0.0.0.0/tcp/6182"
  max_inbound_connections: 100
  identity:
    type: "from_file"
    path: "/opt/aptos/genesis/validator-full-node-identity.yaml"

mempool:
  shared_mempool_max_concurrent_inbound_syncs: 16 # default 4
  max_broadcasts_per_peer: 4 # default 1
  default_failovers: 0 # default 3
  shared_mempool_batch_size: 200 # default 100
  shared_mempool_tick_interval_ms: 10 # default 50

api:
  enabled: true
  address: "0.0.0.0:8080"
